const ConnectionStatus = {
    Disconnected: "Disconnected",
    Failed: "Failed",
    Unhealthy: "Unhealthy",
    Healthy: "Healthy",
    "0": "Disconnected",
    "1": "Failed",
    "2": "Unhealth",
    "3": "Healthy"
};

const Command = {
    None: "None", // 255,
    Manual: "Manual", // = 0,
    ReturnToLaunch: "ReturnToLaunch",
    Stabilize: "Stabilize",
    FlyByWireA: "FlyByWireA",
    FlyByWireB: "FlyByWireB",
    FlyByGCS: "FlyByGCS",
    Circle: "Circle",
    WayPoint: "WayPoint",
    LoiterUnlimited: "LoiterUnlimited",
    LoiterTurns: "LoiterTurns",
    LoiterTime: "LoiterTime",
    LoiterAltitude: "LoiterAltitude",
    ApproachLanding: "ApproachLanding",
    Land: "Land",
    TakeOff: "TakeOff",
    TaxiStop: "TaxiStop",
    TaxiToPoint: "TaxiToPoint",
    TaxiSpeedUp: "TaxiSpeedUp",
    SetServoAngle: "SetServoAngle",
    Sit: "Sit",
    SetFlightParam: "SetFlightParam",
    Rescue: "Rescue",
    Jump: "Jump",
    VtolStabilize: "VtolStabilize",
    VtolHoverByWire: "VtolHoverByWire",
    VtolSpeedHold: "VtolSpeedHold",
    VtolPositionHold: "VtolPositionHold",
    VtolSpeedUp: "VtolSpeedUp",
    VtolTakeOff: "VtolTakeOff",
    VtolLand: "VtolLand",
    VtolHoverTime: "VtolHoverTime",
    RequestDeviceAction: "RequestDeviceAction",
    Launch: "Launch",
    ChuteLand: "ChuteLand",
    VtolTest: "VtolTest",

    "-1": "None",
    "255": "None",
    "0": "Manual", // = 0,
    "1": "ReturnToLaunch",
    "2": "Stabilize",
    "3": "FlyByWireA",
    "4": "FlyByWireB",
    "5": "FlyByGCS",
    "6": "Circle",
    "7": "WayPoint",
    "8": "LoiterUnlimited",
    "9": "LoiterTurns",
    "10": "LoiterTime",
    "11": "LoiterAltitude",
    "12": "ApproachLanding",
    "13": "Land",
    "14": "TakeOff",
    "15": "TaxiStop",
    "16": "TaxiToPoint",
    "17": "TaxiSpeedUp",
    "18": "SetServoAngle",
    "19": "Sit",
    "20": "SetFlightParam",
    "21": "Rescue",
    "22": "Jump",
    "23": "VtolStabilize",
    "24": "VtolHoverByWire",
    "25": "VtolSpeedHold",
    "26": "VtolPositionHold",
    "27": "VtolSpeedUp",
    "28": "VtolTakeOff",
    "29": "VtolLand",
    "30": "VtolHoverTime",
    "31": "RequestDeviceAction",
    "32": "Launch",
    "33": "ChuteLand",
    "34": "VtolTest"
}


const CommandLookup = {
    None: 255,
    Manual: 0,
    ReturnToLaunch: 1,
    Stabilize: 2,
    FlyByWireA: 3,
    FlyByWireB: 4,
    FlyByGCS: 5,
    Circle: 6,
    WayPoint: 7,
    LoiterUnlimited: 8,
    LoiterTurns: 9,
    LoiterTime: 10,
    LoiterAltitude: 11,
    ApproachLanding: 12,
    Land: 13,
    TakeOff: 14,
    TaxiStop: 15,
    TaxiToPoint: 16,
    TaxiSpeedUp: 17,
    SetServoAngle: 18,
    Sit: 19,
    SetFlightParam: 20,
    Rescue: 21,
    Jump: 22,
    VtolStabilize: 23,
    VtolHoverByWire: 24,
    VtolSpeedHold: 25,
    VtolPositionHold: 26,
    VtolSpeedUp: 27,
    VtolTakeOff: 28,
    VtolLand: 29,
    VtolHoverTime: 30,
    RequestDeviceAction: 31,
    Launch: 32,
    ChuteLand: 33,
    VtolTest: 34
}
