/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_content_delivery_bucket": "cognito-20210705152557-hostingbucket-dev",
    "aws_content_delivery_bucket_region": "eu-west-1",
    "aws_content_delivery_url": "https://d1kbh87xp32onx.cloudfront.net",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "ampddb-dev",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:8cafba13-39d3-41ee-b184-a992b38fffe5",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_afn1sXhIt",
    "aws_user_pools_web_client_id": "49vlmf88p2agmc50ir60lmucp4",
    "oauth": {}
};


export default awsmobile;